### ISSUE TITLE
Check Problem from docker-mailserver:  config_overrides[$key]: bad array subscript

### ISSUE THREAD

**Issue by alinmear** [alinmear/docker-configomat#5]
https://github.com/tomav/docker-mailserver/issues/680

Make TestCase with following env variables:
```
LDAP_RESULT_ATTRIBUTE: mail
DOVECOT_HOSTS: "myMagicLdap"
DOVECOT_PASS_ATTRS: "uid=user,userPassword=password"
DOVECOT_PASS_FILTER: "(&(objectClass=mailAccount)(uid=%n))"
DOVECOT_USER_ATTRS: "=home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir"
DOVECOT_USER_FILTER: "(&(objectClass=mailAccount)(uid=%n))"
```

**Comment by johansmitsnl** [comment]
Is there an update on this issue?

**Comment by alinmear** [comment]
@johansmitsnl, the problem occurs with the line `DOVECOT_USER_ATTRS: "=home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir"` and the `=` characters.

**Comment by alinmear** [comment]
Should be fixed.

Closed.

**Comment by BirgerK** [comment]
Like mentioned in the other [issue](https://github.com/tomav/docker-mailserver/issues/680#issuecomment-381678171), i think the issue is not fixed.

The exception ist still happening.

**Comment by BirgerK** [comment]
For getting this result, I'm using the following minimal example:

```
docker run --hostname="localhost.com" -it -e LDAP_RESULT_ATTRIBUTE="mail" -e DOVECOT_HOSTS="myMagicLdap" -e DOVECOT_PASS_ATTRS="uid=user,userPassword=password" -e DOVECOT_PASS_FILTER="(&(objectClass=mailAccount)(uid=%n))" -e DOVECOT_USER_ATTRS="=home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir" -e DOVECOT_USER_FILTER="(&(objectClass=mailAccount)(uid=%n))" -e ENABLE_LDAP=1 tvial/docker-mailserver:latest
```

When calling `env` in that running container, there is this variable:
```
DOVECOT_USER_ATTRS==home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir
```
Maybe that's the problem?

**Comment by alinmear** [comment]
@BirgerK can you please post the output of the dovecot config files. Opening this issue again, till we finally have a solution for it.

**Comment by alinmear** [comment]
The strange thing about this is, that with the last commit the issue should have been fixed. See the bats test `@test "#5 Key Value 3"` which is working.

**Comment by BirgerK** [comment]
Well yeah, I saw the test.

This are some contents:
```
# cat /etc/postfix/ldap-domains.cf
bind             = yes
bind_dn          = cn=admin,dc=domain,dc=com
bind_pw          = admin
query_filter =
result_attribute = mail
search_base      = ou=people,dc=domain,dc=com
server_host      = mail.domain.com
start_tls        = no
version          = 3
```
```
# cat /etc/dovecot/dovecot-ldap.conf.ext
base                = ou=people,dc=domain,dc=com
default_pass_scheme = SSHA
dn                  = cn=admin,dc=domain,dc=com
dnpass              = admin
hosts               = mail.domain.com
tls                 = no
ldap_version        = 3
pass_attrs          = uniqueIdentifier=user,userPassword=password
pass_filter         = (&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
user_attrs          = mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
user_filter         = (&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
```

I just took again a look on the error-message:
```
/usr/local/bin/configomat.sh: line 29: config_overrides[$key]: bad array subscript
```
It says that something is wrong in line 29. But in your fixed version in line 29 the array `config_overrides` is not handled. Seems like the image is still using the old version?

Seems like the configomat-submodule was not properly updated. I'll write it to the other issue.

I'm sorry for taking your time!
